---
title: "dev"
author: "Will Schulz"
date: "6/10/2022"
output: html_document
---

```{r}
devtools::install_github("willschulz/panic")
```



```{r}

 /$$$$$$$   /$$$$$$  /$$   /$$ /$$ /$$$$$$$$       /$$$$$$$   /$$$$$$  /$$   /$$ /$$$$$$  /$$$$$$ 
| $$__  $$ /$$__  $$| $$$ | $$| $/|__  $$__/      | $$__  $$ /$$__  $$| $$$ | $$|_  $$_/ /$$__  $$
| $$  \ $$| $$  \ $$| $$$$| $$|_/    | $$         | $$  \ $$| $$  \ $$| $$$$| $$  | $$  | $$  \__/
| $$  | $$| $$  | $$| $$ $$ $$       | $$         | $$$$$$$/| $$$$$$$$| $$ $$ $$  | $$  | $$      
| $$  | $$| $$  | $$| $$  $$$$       | $$         | $$____/ | $$__  $$| $$  $$$$  | $$  | $$      
| $$  | $$| $$  | $$| $$\  $$$       | $$         | $$      | $$  | $$| $$\  $$$  | $$  | $$    $$
| $$$$$$$/|  $$$$$$/| $$ \  $$       | $$         | $$      | $$  | $$| $$ \  $$ /$$$$$$|  $$$$$$/
|_______/  \______/ |__/  \__/       |__/         |__/      |__/  |__/|__/  \__/|______/ \______/ 
                                                                                                  
                                                                                                  
                                                                                                  

```



```{r}
dontpanic <- " /$$$$$$$   /$$$$$$  /$$   /$$ /$$$$$$  /$$$$$$ \n| $$__  $$ /$$__  $$| $$$ | $$|_  $$_/ /$$__  $$\n| $$  \\ $$| $$  \\ $$| $$$$| $$  | $$  | $$  \\__/\n| $$$$$$$/| $$$$$$$$| $$ $$ $$  | $$  | $$      \n| $$____/ | $$__  $$| $$  $$$$  | $$  | $$      \n| $$      | $$  | $$| $$\\  $$$  | $$  | $$    $$\n| $$      | $$  | $$| $$ \\  $$ /$$$$$$|  $$$$$$/\n|__/      |__/  |__/|__/  \\__/|______/ \\______/ "

cat(dontpanic)

writeLines(dontpanic, con = "inst/ascii/dont_panic.txt")

```



```{r}
panic <- " /$$$$$$$   /$$$$$$  /$$   /$$ /$$ /$$$$$$$$       /$$$$$$$   /$$$$$$  /$$   /$$ /$$$$$$  /$$$$$$ \n| $$__  $$ /$$__  $$| $$$ | $$| $/|__  $$__/      | $$__  $$ /$$__  $$| $$$ | $$|_  $$_/ /$$__  $$\n| $$  \\ $$| $$  \\ $$| $$$$| $$|_/    | $$         | $$  \\ $$| $$  \\ $$| $$$$| $$  | $$  | $$  \\__/\n| $$  | $$| $$  | $$| $$ $$ $$       | $$         | $$$$$$$/| $$$$$$$$| $$ $$ $$  | $$  | $$      \n| $$  | $$| $$  | $$| $$  $$$$       | $$         | $$____/ | $$__  $$| $$  $$$$  | $$  | $$      \n| $$  | $$| $$  | $$| $$\\  $$$       | $$         | $$      | $$  | $$| $$\\  $$$  | $$  | $$    $$\n| $$$$$$$/|  $$$$$$/| $$ \\  $$       | $$         | $$      | $$  | $$| $$ \\  $$ /$$$$$$|  $$$$$$/\n|_______/  \\______/ |__/  \\__/       |__/         |__/      |__/  |__/|__/  \\__/|______/ \\______/ \n                                                                                                  "

cat(panic)

writeLines(panic, con = "inst/ascii/dont_panic.txt")

```


```{r}
panic::panic()

panic::dontPanic()

```


```{r}
panicWhen <- function(panic_condtion, mins = 60, panic_banner = TRUE, dontpanic_banner = TRUE, print_time = TRUE){
  if (!is.logical(panic_condtion)) {stop("panic_condtion must be TRUE or FALSE")}
  if (print_time) {message("Checking at ", Sys.time(), "...")}
  if (panic_condtion) {
    panic::panic(mins = mins, banner = panic_banner)
    } else {
      if (dontpanic_banner) {
        panic::dontPanic()
      }
    }
}

rnorm(1)>2

panicWhen(FALSE)
panicWhen(TRUE)

while(1<2){
  panicWhen(rnorm(1)>2)
  Sys.sleep(1)
}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```


```{r}


```





